title: Hello! I'm Pabitra Padhy
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pabitra Padhy # add your name
author-img: pabitra.jpg # add your photo
about-author: I am a Game Programmer. # add description
social-twitter: pabitrapadhy # add your Twitter handle
social-facebook: pabitrapadhypage # add your Facebook handle
social-github: pabitrapadhy # add your Github handle
social-linkedin: pabitrapadhypage # add your Linkedin handle
social-email: pabitrapadhycse@gmail.com # add your Email address

# Disqus
discus-identifier: pabitrapadhy # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
